steps:
  - name: 'thyrlian/android-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo y | sdkmanager --licenses || true
        gradle assembleRelease

artifacts:
  objects:
    location: 'gs://arched-science-453116-h5_cloudbuild/apk/'
    paths: ['app/build/outputs/apk/release/*.apk']
