steps:
  - name: 'thyrlian/android-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e

        # Aceita todas as licenças usando os executáveis nativos do PATH
        yes | sdkmanager --licenses || true

        # Se o gradlew existir usa ele, senão usa o gradle instalado no container
        if [ -f "./gradlew" ]; then
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon
        else
          gradle assembleRelease --no-daemon
        fi

artifacts:
  objects:
    location: 'gs://arched-science-453116-h5_cloudbuild/apk/'
    paths: ['app/build/outputs/apk/release/*.apk']
